# Generated by Django 3.2.8 on 2021-10-23 15:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='category title')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='product title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='product price')),
                ('short_description', models.CharField(max_length=255, verbose_name='product short description')),
                ('description', models.TextField(verbose_name='product description')),
                ('pub_datetime', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='product category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ('-pub_datetime', 'title'),
            },
        ),
    ]
