# Generated by Django 3.2.8 on 2021-10-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-pub_datetime', 'title'), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
